name: "pipeline"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: 'clone-repo'
        uses: actions/checkout@v2

      - name: 'clone-submodule'
        uses: actions/checkout@v2
        with:
          repository: test-submodule-m/test-submodule
          ssh-key: ${{ secrets.TEST }}
          path: src/core
          ref: main
          submodules: 'recursive'

      - name: 'set nodejs'
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 'install dependences'
        run: npm install --no-audit --no-found --no-optional
        
      - name: 'build'
        run: npm run build  