name: "pipeline"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: test-submodule-m/test-submodule
          ssh-key: ${{ secrets.TEST }}
          submodules: 'true'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: 'install dependences'
        run: npm install
      - name: 'build'
        run: npm run build  